/// Load Data From API
export const FETCH_REQUEST_PRODUCT='FETCH_REQUEST_PRODUCT'
export const SUCCESS_PRODUCT='SUCCESS_PRODUCT'
export const FAILED_PRODUCT='FAILED_PRODUCT'

export const FETCH_REQUEST_CATEGORY='FETCH_REQUEST_CATEGORY'
export const SUCCESS_CATEGORY='SUCCESS_CATEGORY'
export const FAILED_CATEGORY='FAILED_CATEGORY'
export const UPDATE_CATEGORY='UPDATE_CATEGORY'

export const ADD_ITEM_INTO_CART='ADD_ITEM_INTO_CART';
export const INCRESE_PRODUCT_QUANTITY='INCRESE_PRODUCT_QUANTITY';

export const DECRESE_PRODUCT_QUANTITY='DECRESE_PRODUCT_QUANTITY';

